baseURL = "http://route-to-excellence-pblsnt.s3-website-us-east-1.amazonaws.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Route to Excellence"
theme = "hugo-theme-learn-master"
defaultContentLanguageInSubdir = true
uglyurls = true

[params]
    description = "A place of excellence"
    author = "Pablo"
    showVisitedLinks = true

[Languages]
[Languages.en]
title = "Route to Excellence"
weight = 1
languageName = "English"

[Languages.fr]
title = "Route d'excellence"
weight = 2
languageName = "Français"

